// Demonstration data, not a directory of real studios or public offers.
export const locations = [
  {
    id: "loft",
    slug: "loft",
    name: "Loft 01",
    type: "Лофт",
    shortDescription:
      "Тёплый свет, большие окна и пространство для ваших историй.",
    description:
      "Демонстрационный зал с панорамными окнами, фактурными стенами и мягкой зоной. Подходит для портретов, контента брендов и небольших команд.",
    price: 15000,
    area: 90,
    capacity: 12,
    address: "Астана · демонстрационная локация",
    amenities: [
      "Естественный свет",
      "Гримёрная",
      "Wi-Fi",
      "Реквизит",
      "Парковка",
    ],
    image: "/images/loft.svg",
    gallery: ["/images/loft.svg", "/images/cyclorama.svg"],
  },
  {
    id: "cyclorama",
    slug: "cyclorama",
    name: "White Space",
    type: "Циклорама",
    shortDescription: "Чистый белый фон, на котором ваша идея — главное.",
    description:
      "Демонстрационная белая циклорама для предметной и fashion-съёмки. Постоянный свет и базовые стойки входят в указанную демонстрационную стоимость.",
    price: 20000,
    area: 120,
    capacity: 15,
    address: "Астана · демонстрационная локация",
    amenities: [
      "Циклорама",
      "Постоянный свет",
      "Гримёрная",
      "Wi-Fi",
      "Зона отдыха",
    ],
    image: "/images/cyclorama.svg",
    gallery: ["/images/cyclorama.svg", "/images/loft.svg"],
  },
  {
    id: "rooftop",
    slug: "rooftop",
    name: "Skyline Rooftop",
    type: "Крыша",
    shortDescription: "Город, небо и кадры с новым ракурсом.",
    description:
      "Демонстрационная открытая площадка с видом на город. Возможность съёмки зависит от погоды; администратор уточняет условия до подтверждения заявки.",
    price: 18000,
    area: 150,
    capacity: 10,
    address: "Астана · демонстрационная локация",
    amenities: [
      "Вид на город",
      "Естественный свет",
      "Электричество",
      "Зона отдыха",
    ],
    image: "/images/rooftop.svg",
    gallery: ["/images/rooftop.svg", "/images/garden.svg"],
  },
  {
    id: "garden",
    slug: "garden",
    name: "Secret Garden",
    type: "Сад",
    shortDescription: "Живая зелень и спокойная атмосфера в каждом кадре.",
    description:
      "Демонстрационная площадка с растениями для семейных и lifestyle-съёмок. Доступные зоны и реквизит уточняются перед подтверждением бронирования.",
    price: 12000,
    area: 80,
    capacity: 8,
    address: "Астана · демонстрационная локация",
    amenities: ["Растения", "Естественный свет", "Реквизит", "Wi-Fi"],
    image: "/images/garden.svg",
    gallery: ["/images/garden.svg", "/images/loft.svg"],
  },
  {
    id: "hangar",
    slug: "hangar",
    name: "Industrial Hall",
    type: "Ангар",
    shortDescription: "Масштаб, фактуры и свобода для смелых проектов.",
    description:
      "Демонстрационный просторный зал для клипов, командных и предметных съёмок. Дополнительное оборудование и сложные постановки согласуются с администратором.",
    price: 25000,
    area: 250,
    capacity: 25,
    address: "Астана · демонстрационная локация",
    amenities: [
      "Высокие потолки",
      "Грузовой вход",
      "Электричество",
      "Парковка",
      "Гримёрная",
    ],
    image: "/images/hangar.svg",
    gallery: ["/images/hangar.svg", "/images/cyclorama.svg"],
  },
];
